In [27]:
#Question1
import numpy as np
original_list = (12.23,13.32,100,36.32)
print(original_list)
converted_array = np.array(original_list)
print(converted_array)

(12.23, 13.32, 100, 36.32)
[ 12.23  13.32 100.    36.32]


In [41]:
#Question2
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [38]:
#Question3
import numpy as np
zeroarray = np.zeros(10)
print(zeroarray)
zeroarray[5]=1
print(zeroarray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [39]:
#Question4
import numpy as np
np.arange(12,39)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [37]:
#Question5
origarray=np.arange(12,21)
print(origarray)
revarray=origarray[::-1] #start:stop:step
print(revarray)

[12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12]


In [36]:
#Question6
import numpy as np
a=[1,2,3,4]
intarray=np.array(a)
print(intarray)
floatarray=np.asfarray(intarray)
print(floatarray)

[1 2 3 4]
[1. 2. 3. 4.]


In [35]:
#Question7
import numpy as np
arrayex=np.ones((5,5))
print(arrayex)
arraynew=arrayex[1:-1,1:-1]
#print(f"list subset {arraynew}")
#arraynew[:]=3
print(arraynew)
#from first 2.row to last 2.row, from first 2.column until last 2.column
arrayex[1:-1,1:-1]=0
print(arrayex)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
#Question8
import numpy as np
myarray = np.ones((3,3))
print(myarray)
myarray2 = np.zeros((myarray.shape[0]+2, myarray.shape[1]+2))
print(myarray2)
myarray2[1:-1,1:-1]=1
#or myarray2[1:-1,1:-1]=myarray
print(myarray2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
#Question9
import numpy as np
print("Checkerboard:")
checker_board = np.zeros((8,8))
checker_board[1::2,::2] = 1
checker_board[::2,1::2] = 1
print(checker_board)

Checkerboard:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [18]:
#Question10
import numpy as np
list = (1,2,3,4,5,6,7,8)
arr1 = np.array(list)
tuple = ((8,4,6),(1,2,3))
arr2 = np.array(tuple)
print(arr1)
print(arr2)

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


In [192]:
#Question11
array = [10,20,30]
np.append(array,[[40,50,60],[70,80,90]])


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
 #Question 12
feh_arr = [0,12,45.21,34,99.91]
cel_arr = []
for i in feh_arr:
    cel_arr.append((5*(i-32)/9))
    print(i)
print(cel_arr)
    #feh_array[i]=(9/5*cel_array[i])-32


0
12
45.21
34
99.91
[-17.77777777777778, -11.11111111111111, 7.33888888888889, 1.1111111111111112, 37.727777777777774]


In [20]:
#Question13
import numpy as np
a = [1,2,3]
a = np.array(a)
print("Size of the array",a.size)
print("Lenght of one array element",a.itemsize)
print("Total Byte consumed by the elements",a.nbytes)

Size of the array 3
Lenght of one array element 8
Total Byte consumed by the elements 24


In [14]:
#Question14
import numpy as np
arr1 = [0,10,20,40, 60]
arr2 = [10,30,40]
common = []
for i in arr1:
    for k in arr2:
        if i == k:
            common.append(i)
print(common)

[10, 40]


In [15]:
#Question15
import numpy as np
arr1 = np.array([10, 10, 20, 20, 30, 30])
print("Unique elements of the array1:",np.unique(arr1))
arr2 = np.array([[1, 1], [2, 3]])
print("Unique elements of the array2:",np.unique(arr2))

Unique elements of the array1: [10 20 30]
Unique elements of the array2: [1 2 3]


In [83]:
#Question16
import numpy as np
arr1 = np.array([0,10,20,40,60,80])
arr2 = np.array([10, 30,40,50,60])
print(np.setdiff1d(arr1,arr2))

[ 0 20 80]


In [85]:
#Question17
import numpy as np
arr2 = np.array([10, 30,40,50,70])
print(np.setxor1d(arr1, arr2))

[ 0 20 30 50 60 70 80]


In [86]:
#Question18
import numpy as np
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = [10, 30, 40, 50, 70]
print(np.union1d(arr1, arr2))

[ 0 10 20 30 40 50 60 70 80]


In [87]:
#Question19
import numpy as np
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


In [19]:
#Question20
import numpy as np
array = [1,2,3,4,5,6]
arr_max = array[0]
arr_min = array[0]
for i in array:
    if i>arr_max:
        arr_max = i
    if i<arr_min:
        arr_min = i
print("The largest value is:",arr_max)
print("The smallest value is:",arr_min)

The largest value is: 6
The smallest value is: 1


In [91]:
#Question21
import numpy as np
values = np.array([[0, 10, 20], [20, 30, 40]])
print("Values bigger than 10 =", values[values>10])
print("Their indices are ", np.nonzero(values > 10))

Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [17]:
#Question22
import numpy as np
arrofZeros = np.zeros((1,2))
arrofOnes = np.ones((1,2))
print("Array of Zeros:",arrofZeros)
print("Array of Ones:",arrofOnes)

Array of Zeros: [[0. 0.]]
Array of Ones: [[1. 1.]]


In [104]:
#Question23
import numpy as np
print(np.ravel([[10,20,30],[20,40,50]]))

[10 20 30 20 40 50]


In [106]:
#Question24
import numpy as np
array = [[1,2],[3,4],[5,6]]
print(np.reshape(array,(2,3)))

[[1 2 3]
 [4 5 6]]


In [10]:
#Question25
import numpy as np
arrayInt = [[2,4,6],[6,8,10]]
arrayInt = np.array(arrayInt)
print('Original Array',arrayInt)
print(arrayInt.dtype)
arrayInt = arrayInt.astype('float64')
print('Updated Array',arrayInt)
print(arrayInt.dtype)

Original Array [[ 2  4  6]
 [ 6  8 10]]
int64
Updated Array [[ 2.  4.  6.]
 [ 6.  8. 10.]]
float64


In [117]:
#Question26
import numpy as np
print(np.logspace(2, 5, 20, endpoint = False))

[  100.           141.25375446   199.5262315    281.83829313
   398.10717055   562.34132519   794.32823472  1122.0184543
  1584.89319246  2238.72113857  3162.27766017  4466.83592151
  6309.5734448   8912.50938134 12589.25411794 17782.79410039
 25118.8643151  35481.33892336 50118.72336273 70794.57843841]


In [121]:
#Question27
import numpy as np
arrayof2Da = [[0,1,3],[5,7,9]]
arrayof2Db = [[0,2,4],[6,8,10]]
arrayof2Da = np.array(arrayof2Da)
arrayof2Db = np.array(arrayof2Db)
np.concatenate((arrayof2Da,arrayof2Db),1)

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [131]:
#Question28
import numpy as np
array = np.arange(1, 15)
print(array)
print(np.split(array, [2, 6]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


In [132]:
#Question29
import numpy as np
x = np.arange(16).reshape((4, 4))
print("Original array:",x)
print("After splitting horizontally:")
print(np.hsplit(x, [2, 6]))

Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


In [145]:
#Question30
import numpy as np
array = [[0,10,20],[20,30,40]]
array = np.array(array)
print("The total number of non zero element is:{}".format(np.count_nonzero(array)))

The total number of non zero element is:5


In [147]:
#Question31
import numpy as np
array_x = [[10,20,30],[40,50,60]]
array_x = np.array(array_x)
array_y = [[100],[200]]
array_y = np.array(array_y)
print(np.append(array_x,array_y,axis = 1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [11]:
#Question32
import numpy as np
array = [-1,-4,0,2,3,4,5,-6]
array = np.array(array)
for (i) in array:
       if array[i]<0:
            array[i]=0
print(array)


[ 0 -4  0  2  3  4  5  0]


In [155]:
#Question33
import numpy as np
array = np.array([[1,2,3], [4,5,np.nan], [7,8,9], [1, 0, 1]])
print("The array:", array)
print(array[~np.isnan(array).any(axis = 1)])

The array: [[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 7.  8.  9.]
 [ 1.  0.  1.]]
[[1. 2. 3.]
 [7. 8. 9.]
 [1. 0. 1.]]


In [12]:
#Question34
import numpy as np
x = np.array([97,101,105,111,117])
y = np.array(['a','e','i','o','u'])
for i in range(0,len(x)):
       if(x[i]>100 and x[i]<110):
            print(y[i])


e
i


In [196]:
#Question35
import numpy as np
array = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
elements, counts= np.unique(array, return_counts = True)
print("Frequency of unique values of the said array:")
print(np.asarray((elements, counts)))

Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [209]:
#Question36
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array[:,[1,2]])

[[2 3]
 [5 6]
 [8 9]]


In [210]:
#Question37
import numpy as np
array = [1,0,2,0,3,0,4,5,6,7,8]
array = np.array(array)
for i in range(0,len(array)):
    if array[i]==0:
        print(i)



1
3
5
